### ISSUE TITLE
Plugin install fails...

### ISSUE THREAD

**Issue by MrMxyzptlk** [lubeda/Loupedeck-HomeAssistantPlugin#4]
![image](https://user-images.githubusercontent.com/1753001/210869982-d2bd6eff-e6e5-4ac1-bc53-e82d405c050c.png)

**Comment by MrMxyzptlk** [comment]
Not sure where to check for the install log?

**Comment by lubeda** [comment]
Do you have the latest version of the loupdeck software? ware you on Windows?
What about your virus scaner?
Do you use the latest plugin version? https://github.com/lubeda/Loupedeck-HomeAssistantPlugin/releases/download/v0.5/HomeAssistantPlugin_0.5.lplug4

**Comment by MrMxyzptlk** [comment]
Yes, latest version of OS, Loupe-deck, and plugin. Both Mac and Windows fail; generic failure message.
No Anti-Virus software or firewall.
