### ISSUE TITLE
What am I missing or has something changed?

### ISSUE THREAD

**Issue by martinkwright** [lubeda/Loupedeck-HomeAssistantPlugin#5]
Latest verion of the plugin installed. I've added the long live token to a homeassistant.json file and placed it in the "AppData\Local\Loupedeck\Plugins\HomeAssistant\win\" . Loupedeck starts, plugin is there, go to call a service, I can populate name but no services or entities display. 

This in the homeassistant.json file.
------------------------------------------
```
{
  "token": "Pasted my token",
  "url": "http://my.homeassistanturl:8123/api/",
  "entries": [
    {
      "service": "light.turn_on",
      "entities": [
        "light.bl606a0_18b905c0d5af",
        "light.mkw_office_tv_led",
        "light.mkw_key_light"
      ]
    },
    {
      "service": "switch.toggle",
      "entities": [
        "switch.ofloor",
        "switch.kitchen",
        "switch.se_fan"
      ]
    }
  ]
}
``` 

------------------------------------------

**Comment by lubeda** [comment]
Hi,
your json looks good!
the newest version of lookdeck changed the ui a little. 
![image from my system](https://user-images.githubusercontent.com/17859549/225707788-3cdc521b-ea55-48d5-ae49-73f7d9ccbf90.png)

First select the homeassistant plugin, then "Call Service", in your example e.g. "light.turn_on", then the entity e.g. "light.bl606a0_18b905c0d5af" name your button and you're done.

**Comment by lubeda** [comment]
I see, your filepath is **wrong!!**

place the file in `%userprofile%\.loupedeck\homeassistant\` as `homeassistant.json`

e.g. `c:\Users\_MartinK_\.loupedeck\homeassistant\homeassistant.json`

**Comment by martinkwright** [comment]
That was exactly it. Thank you for clarifying the file path. Apologies... rtfm, I see that now.
